---
- hosts: all
  become: True
  tasks:
    - name: Create a tarball to copy for deployment
      community.general.archive:
        path: ./docroot
        dest: ./deploy.tar.gz
      delegate_to: localhost
      become: False
    - name: Unpack the tarball to the remote system
      ansible.builtin.unarchive:
        src: deploy.tar.gz
        dest: /var/www/html
        owner: www-data
        group: www-data
    - name: Fix the symlink created by plerd
      ansible.builtin.file:
        dest: /var/www/html/docroot/index.html
        src: /var/www/html/docroot/recent.html
        state: link
        force: True
    - name: Cleanup the tarball
      ansible.builtin.file:
        path: ./deploy.tar.gz
        state: absent
      delegate_to: localhost
      become: False
